name: Google TTS Workflow
on:
  workflow_dispatch:
jobs:
  tts:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    env:
      GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
    steps:
      - uses: actions/checkout@v4
      - uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
      - uses: google-github-actions/setup-gcloud@v2
      - name: Export access token
        run: |
          echo "GOOGLE_TTS_TOKEN=$(gcloud auth print-access-token)" >> $GITHUB_ENV
      - name: Sanity call TTS
        run: |
          echo '{"input":{"text":"Hello from GitHub Actions."},"voice":{"languageCode":"en-US","name":"en-US-Neural2-D"},"audioConfig":{"audioEncoding":"MP3"}}' > request.json
          curl -s -X POST \
            -H "Authorization: Bearer $GOOGLE_TTS_TOKEN" \
            -H "Content-Type: application/json" \
            -d @request.json \
            "https://texttospeech.googleapis.com/v1/text:synthesize" > response.json
          test -s response.json
      - name: Upload response
        uses: actions/upload-artifact@v4
        with:
          name: tts-response
          path: response.json